version: "3"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
    ports:
    - "5432:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    links:
      - db
    depends_on:
      - db
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8000:8000"
    # command: "sh start.sh"
  web:
    image: nginx
    links:
      - app
    depends_on:
      - app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"