version: "3"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
    ports:
    - "5432:5432"
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    image: "node:8.11"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/home/node/app
    ports:
      - "8000:8000"
      - "5858:5858"
    links:
    - "db"
    command: "sh start.sh"
  web:
    image: nginx
    links:
      - app
    depends_on:
      - app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"